global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
      - names: ['RENDER_SERVICE_NAME-discovery']
        port: 9090
        type: A
        refresh_interval: 5s